---
interval: 30s
time_series:
  - series: up{pod="database", namespace="backend"}
    values: 1+0x100
    stream: 1+0
  - series: memory_usage{namespace="backend"}
    values: 200+0x100
    stream: 200+0
